<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Rta.Disc\Rta.Disc.csproj" />
    <ProjectReference Include="..\..\src\Rta.Formats\Rta.Formats.csproj" />
  </ItemGroup>
</Project>
